source = $HOME/.config/hypr/colors.conf
source = $HOME/.config/hypr/mocha.conf

$accent = $text
$accentAlpha = $text
$font = IosevkaNerdFont mono
$back = $basea

# GENERAL
general {
  hide_cursor = false
}

# BACKGROUND
background {
  monitor =
  path = $HOME/Pictures/Wallpapers/gruvbox-forest.jpg
  blur_passes = 3
  blur_size = 2
  brightness = 0.9

}

# HOUR
label {
  monitor =
  text = cmd[update:1000] echo -e "$(date +"%H:%M")"
  text_align = center
  color = rgba(255, 255, 255, 0)
  position = -20, 0
  halign = right
  valign = top
  font_family = AlfaSlabOne
  font_size = 150
}


# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"$(date +"%A, %B %d %Y |%I:%M%p")"
  color = $accent
  font_size = 50
  font_family = BebasNeue 
  position = 20, 30
  halign = left
  valign = bottom
}

# USER AVATAR
image {
  monitor =
  path = /home/denko/Pictures/PFP/ppafp.jpg
  size = 130
  border_color = $accent
  outline_thickness = 2
  position = 20, -350
  halign = left
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 45
  outline_thickness = 0
  dots_text_format =  
  dots_size = 0.3
  dots_spacing = 4
  dots_center = true
  outer_color = $accent
  inner_color = $back
  font_color = $accent
  font_family = $font
  font_size = 70s
  fade_on_empty = false
  placeholder_text =  ┬┴┬┴┤•ᴥ•ʔ├┬┴┬┴
  hide_input = false
  check_color = rgba(255, 0, 0, 0.47)
  fail_color = rgba(230, 126, 128, 0.62)
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, 0
  halign = center
  valign = center
}
label {
    monitor =
    text = cmd[update:8000] printf ' '
    color = ffffff
    font_size = 13
    font_family = $font
    position = 0, 10
    halign = left
    valign = bottom
    text_align = center
}