source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/startup.conf
source = ~/.config/hypr/modules/enviroment.conf
source = ~/.config/hypr/modules/decorations.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/keybinds.conf
source = ~/.config/hypr/modules/animation.conf
source = ~/.config/hypr/modules/windowrules.conf
