# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e5e2de"

# Title color for boxes
theme[title]="#dddec3"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c8c7ba"

# Background color of selected item in processes box
theme[selected_bg]="#dddec3"

# Foreground color of selected item in processes box
theme[selected_fg]="#30321f"

# Color of inactive/disabled text
theme[inactive_fg]="#c8c7bc"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ead7e7"

# Cpu box outline color
theme[cpu_box]="#929187"

# Memory/disks box outline color
theme[mem_box]="#929187"

# Net up/down box outline color
theme[net_box]="#929187"

# Processes box outline color
theme[proc_box]="#929187"

# Box divider line and small boxes line color
theme[div_line]="#47473f"

# Temperature graph colors
theme[temp_start]="#c8c7ba"
theme[temp_mid]="#dddec3"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#c8c7ba"
theme[cpu_mid]="#dddec3"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#c8c7ba"
theme[free_mid]=""
theme[free_end]="#494a40"

# Mem/Disk cached meter
theme[cached_start]="#ead7e7"
theme[cached_mid]=""
theme[cached_end]="#cdbbcb"

# Mem/Disk available meter
theme[available_start]="#dddec3"
theme[available_mid]=""
theme[available_end]="#c1c2a8"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#c8c7ba"
theme[download_mid]="#dddec3"
theme[download_end]="#ead7e7"

# Upload graph colors
theme[upload_start]="#c8c7ba"
theme[upload_mid]="#dddec3"
theme[upload_end]="#ead7e7"