source = ~/.config/hypr/mocha.conf
general {
    gaps_in = 15
    gaps_out = 15

    border_size = 3
    # Borders
    col.active_border = rgba(cdd6f4ff) 
    col.inactive_border = rgba(1e1e2eff)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle

}
misc {
    initial_workspace_tracking = 1
    middle_click_paste = false
}


dwindle {

    force_split = 2
}

# Decorations
decoration {
    rounding = 10
    dim_special = 0.3
    active_opacity = 1.0
    inactive_opacity = 0.9
    border_part_of_window = true

    shadow {
        enabled = on
        range = 30
        scale = 1.0
        render_power = 4
        color = rgba(1e1e2e55)
    }


    blur {
        enabled = true
        size = 7
        passes = 3
        new_optimizations = true
        ignore_opacity = true
        xray = false
    }
}
