input {
    kb_layout = us
    kb_variant = altgr-intl
    kb_model =
    kb_options = 
    kb_rules =
    scroll_button_lock = false
    scroll_method = on_button_down
    scroll_button = 0
    follow_mouse = 1
    natural_scroll = true
    sensitivity = -0.45

    touchpad {
        natural_scroll = false
    }
}


device {
    name = epic-mouse-v1
    sensitivity = 0
}

# Layouts
dwindle {
    pseudotile = true
    preserve_split = true
}
master {
    new_status = master
}