$terminal = kitty
$fileManager = dolphin
$menu = rofi --show drun


exec-once = swww-daemon --format xrgb
exec-once = sleep 3 && play '~/Music/Sounds/start.mp3' & 
exec-once = ~/.config/scripts/waybar.sh
exec-once = swaync
exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE
exec-once = systemctl --user start hyprland-session.target
exec-once = systemctl start mpd 
exec-once = sleep 3 &&~/Desktop/startup.sh
exec-once = systemctl --user enable opentabletdriver.service --now
exec-once = hypridle
exec-once = hyprpm reload
exec-once = xrdb -merge ~/.Xresources
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = ~/.config/scripts/spotify-notify.sh
exec-once = waypaper --restore