#config location:
# ~/.config/mpd/mpd.conf

#default directory is XDG spec
music_directory "/home/denko/Music"
#playlist directory "~/.config/mpd/playlists"
playlist_directory "/home/denko/Music/Playlist"

auto_update "yes" #automatically updates db
bind_to_address "localhost" #localhost
restore_paused "yes" #startup behavior
max_output_buffer_size "16384"

audio_output {
    type "pulse"
    name "pulse"
}
#audio visualizer setup
audio_output {
    type "fifo"
    name "my_fifo"
    path "/tmp/mpd.info"
    format "44100:16:2"
}

